// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc30Jp-sRjQZT-ksYRIisGnzJ33GLdWkg',
    appId: '1:445548873191:web:669902ed1cd53432e06942',
    messagingSenderId: '445548873191',
    projectId: 'fir-7f610',
    authDomain: 'fir-7f610.firebaseapp.com',
    storageBucket: 'fir-7f610.appspot.com',
    measurementId: 'G-JF096KSFZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa4LTmZqHYXs3-FwalaOx68qsHdLi9Ihg',
    appId: '1:445548873191:android:08c7a631d9e5bf78e06942',
    messagingSenderId: '445548873191',
    projectId: 'fir-7f610',
    storageBucket: 'fir-7f610.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPSB26BYAQN9L0okH4AjnYYhPMU6b2niw',
    appId: '1:445548873191:ios:b1c89259438c5c0ee06942',
    messagingSenderId: '445548873191',
    projectId: 'fir-7f610',
    storageBucket: 'fir-7f610.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPSB26BYAQN9L0okH4AjnYYhPMU6b2niw',
    appId: '1:445548873191:ios:b1c89259438c5c0ee06942',
    messagingSenderId: '445548873191',
    projectId: 'fir-7f610',
    storageBucket: 'fir-7f610.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc30Jp-sRjQZT-ksYRIisGnzJ33GLdWkg',
    appId: '1:445548873191:web:d6d404fded11b436e06942',
    messagingSenderId: '445548873191',
    projectId: 'fir-7f610',
    authDomain: 'fir-7f610.firebaseapp.com',
    storageBucket: 'fir-7f610.appspot.com',
    measurementId: 'G-LCV2MZXWEV',
  );
}
